FROM ubuntu:latest

USER root

# COPY ./inspircd.conf /etc/inspircd/inspircd.conf
# COPY ./inspircd/conf.d /etc/
COPY ./inspircd /etc/inspircd

COPY . .

RUN apt update \
    && apt install -y wget

# Ports 6667:6667
EXPOSE 6667/tcp
EXPOSE 6697/tcp
EXPOSE 7000/tcp
EXPOSE 7001/tcp

# RUN ["sh", "sudo ./app/install.sh"]
RUN ["sh", "install.sh"]